frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Settings;
use common\models\Seo;
use common\models\Category;
use common\models\Village;
use common\models\Realt;
use frontend\models\RealtSearch;
use frontend\models\VillageSearch;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\helpers\ArrayHelper;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use common\models\Field;
use yii\data\Pagination;
use common\models\RealtViewRequest;
use common\models\VillageViewRequest;

class CategoryController extends \frontend\components\controllers\FrontController {

	private $_current_category = NULL;

	public function behaviors() {
		$behaviors = [
			'access' => [
				'rules' => [
					[
						'allow' => true,
						'roles' => ['?', '@'], // все
					],
				]
			],
			[
				'class' => 'yii\filters\HttpCache',
//                //    'only' => ['index'],
				'lastModified' => function ($action, $params) {
//                    return 1460095573;
					$q = new \yii\db\Query();
					return strtotime($q->from('realt')->max('updated_at')) + strtotime($q->from('village')->max('updated_at'))+strtotime($q->from('category')->max('updated_at'));
				},
			],
		];

		return array_merge_recursive(parent::behaviors(), $behaviors);
	}

	public function actionView($id) {
		if (!$category = Category::findOne($id)) {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
		$this->_current_category = $category;
		$this->admin_menu[] = [
			'label' => "Категория (id: " . $category->id . ")",
			'url' => ["/admin/category/update", "id" => $category->id]];

		$this->seo->attachModel($category);

		$breadcrumbs = [];

		$p = $category;
		while ($p = $p->parent) {
			$breadcrumbs[] = ['label' => $p->title, 'url' => $p->url];
		}

		$this->seo->breadcrumbs = array_reverse($breadcrumbs);

		$this->data['category'] = $category;
		$this->data['current_page'] = \Yii::$app->request->get('page');

		$this->seo->canonical_url = $category->url . ($this->data['current_page'] ? "?page=" . $this->data['current_page'] : "");

		switch ($category->getContentTypeId()) {
			case Category::TYPE_VILLAGE:
				return $this->showVillages();
				break;
			case Category::TYPE_COTTAGE:
				return $this->showCottage();
				break;
			case Category::TYPE_STEAD:
				return $this->showStead();
			case Category::TYPE_TOWNHOUSE:
				return $this->showTownhouse();
				break;
		}
	}

	public function actionFilter($type_id) {
		switch ($type_id) {
			case Category::TYPE_VILLAGE:;
				return $this->showVillages();
				break;
			case Category::TYPE_COTTAGE:
				return $this->showCottage();
			case Category::TYPE_STEAD:
				return $this->showStead();
			case Category::TYPE_TOWNHOUSE:
				return $this->showTownhouse();
				break;
		}
	}

	private function showVillagesFilter() {
		$searchModel = new VillageSearch();
		if (!empty($this->data['category']) AND $filter = $this->data['category']->getFullFilterArray()) {
			$searchModel->setFilters($filter);
		}

		$searchModel->appendFilters(Yii::$app->request->get('filter', []));

		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		//$dataProvider->sort['defaultOrder'] = ['title' => SORT_ASC];
		$dataProvider->sort = ['defaultOrder' => ['premium' => SORT_DESC, 'sort_order'=>SORT_ASC, 'id' => SORT_ASC]];
		$dataProvider->pagination->defaultPageSize = 35;

		$this->data['models'] = $dataProvider->getModels();
		$this->data['pagination'] = $dataProvider->pagination;
		$this->data['search_model'] = $searchModel;

		// fix для превышения лимита страниц
		if ($dataProvider->pagination->page + 1 != Yii::$app->request->get($dataProvider->pagination->pageParam, 1)) {
			$valid_page = $dataProvider->pagination->page + 1;
			parse_str(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY), $get_params);
			unset($get_params[$dataProvider->pagination->pageParam]);
			return $this->redirect(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) . ($get_params ? "?" . http_build_query($get_params) : ""), 301);
		}

		$this->data['filter'] = Yii::$app->request->get('filter', []);
		$this->data['filter_fields'] = [];
		foreach ([3, 4, 7, 8, 9, 16, 19] as $field_id) {
			$field = Field::findOne($field_id);
			$this->data['filter_fields'][$field_id] = ['values' => ArrayHelper::map($field->getFieldTags()->orderBy('value')->all(), 'id', 'value')];
		}

		if ($this->data['pagination']->page > 0) {
			$this->seo->h1 = $this->seo->h1 . " " . ($this->data['pagination']->page + 1) . " страница каталога объектов недвижимости";

			if (!empty($this->data['category'])) {
				$this->seo->addBreadcrumb(['label' => $this->data['category']->title, 'url' => $this->data['category']->url]);
			} else {
				$this->seo->addBreadcrumb("Фильтр");
			}

			$this->seo->addBreadcrumb(['label' => "Страница " . ($this->data['pagination']->page + 1)]);
		} else {
			if (!empty($this->data['category'])) {
				$this->seo->addBreadcrumb($this->data['category']->title);
			} else {
				$this->seo->addBreadcrumb("Фильтр");
			}
		}

		$this->data['view_request_form'] = $this->viewRequestFormVillage();
	}

	private function showRealtFilter($type_id) {
		$searchModel = new RealtSearch();
		if (!empty($this->data['category']) AND $filter = $this->data['category']->getFullFilterArray()) {
			$searchModel->setFilters($filter);
		}

		$searchModel->appendFilters(Yii::$app->request->get('filter', []));
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		$dataProvider->query->andWhere(['type_id' => $type_id]);
		$dataProvider->pagination->defaultPageSize = 35;


		$this->data['models'] = $dataProvider->getModels();
		$this->data['pagination'] = $dataProvider->pagination;
		$this->data['search_model'] = $searchModel;

		// fix для превышения лимита страниц
		if ($dataProvider->pagination->page + 1 != Yii::$app->request->get($dataProvider->pagination->pageParam, 1)) {
			$valid_page = $dataProvider->pagination->page + 1;
			parse_str(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY), $get_params);
			unset($get_params[$dataProvider->pagination->pageParam]);
			return $this->redirect(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) . ($get_params ? "?" . http_build_query($get_params) : ""), 301);
		}

		$this->data['filter'] = Yii::$app->request->get('filter', []);
		$this->data['filter_fields'] = [];
		foreach ([3, 4, 7, 8, 9, 16, 19] as $field_id) {
			$field = Field::findOne($field_id);
			$this->data['filter_fields'][$field_id] = ['values' => ArrayHelper::map($field->getFieldTags()->orderBy('value')->all(), 'id', 'value')];
		}

		if ($this->data['pagination']->page > 0) {
			$this->seo->h1 = $this->seo->h1 . " " . ($this->data['pagination']->page + 1) . " страница каталога объектов недвижимости";

			if (!empty($this->data['category'])) {
				$this->seo->addBreadcrumb(['label' => $this->data['category']->title, 'url' => $this->data['category']->url]);
			} else {
				$this->seo->addBreadcrumb("Фильтр");
			}

			$this->seo->addBreadcrumb(['label' => "Страница " . ($this->data['pagination']->page + 1)]);
		} else {
			if (!empty($this->data['category'])) {
				$this->seo->addBreadcrumb($this->data['category']->title);
			} else {
				$this->seo->addBreadcrumb("Фильтр");
			}
		}

		$this->data['view_request_form'] = $this->viewRequestFormRealt();
	}

	private function viewRequestFormRealt() {
		$data['model'] = new RealtViewRequest;
		$data['message'] = "";
		$data['success'] = FALSE;
		$data['error'] = FALSE;
		//$reviews_form['model']->scenario = "create_from_front";

		if ($data['model']->load(Yii::$app->request->post())) {
			if ($data['model']->save()) {
				$data['model'] = new RealtViewRequest;
				$data['success'] = TRUE;
				$data['message'] = "Заявка отправлена";
			} else {
				$data['error'] = TRUE;
				$data['message'] = "Проверьте форму на ошибки";
			}
		}

		$data['model']->scenario = "default";
		return $data;
	}

	private function viewRequestFormVillage() {
		$data['model'] = new VillageViewRequest;
		$data['message'] = "";
		$data['success'] = FALSE;
		$data['error'] = FALSE;
		//$reviews_form['model']->scenario = "create_from_front";

		if ($data['model']->load(Yii::$app->request->post())) {
			if ($data['model']->save()) {
				$data['model'] = new VillageViewRequest;
				$data['success'] = TRUE;
				$data['message'] = "Заявка отправлена";
			} else {
				$data['error'] = TRUE;
				$data['message'] = "Проверьте форму на ошибки";
			}
		}

		$data['model']->scenario = "default";
		return $data;
	}

	private function showVillages() {
		$this->showVillagesFilter();
		return $this->render('villages');
	}

//    !!!!!!!!!!!!
//    private function showRealt() {
//        $this->showRealtFilter($this->data['category']->getContentTypeId());
//        $this->data['search_view'] = '_realt_cottage_search';
//        return $this->render('realt');
//    }

	private function showCottage() {
		$this->showRealtFilter(Category::TYPE_COTTAGE);
		$this->data['search_view'] = '_realt_cottage_search';
		return $this->render('realt');
	}

	private function showStead() {
		$this->showRealtFilter(Category::TYPE_STEAD);
		$this->data['search_view'] = '_realt_stead_search';
		return $this->render('realt');
	}

	private function showTownhouse() {
		$this->showRealtFilter(Category::TYPE_TOWNHOUSE);
		$this->data['search_view'] = '_realt_townhouse_search';
		return $this->render('realt');
	}

	/*
	  public function actionExport() {
	  $rows = [];
	  foreach (Category::find()->where(['parent_id' => 0])->orderBy('title')->all() as $cat_1) {
	  $row = [
	  $cat_1->id,
	  $cat_1->title,
	  $cat_1->title,
	  "",
	  "",
	  "",
	  "",

frontend/views/category/_realt_cottage_search.php
<?php

use common\helpers\Html;
use kartik\widgets\ActiveForm;
use common\models\Category;
use yii\helpers\ArrayHelper;
use common\models\CategoryFilter;
?>

<div class="filter clearfix">
    <?php
    $form = ActiveForm::begin([
                'method' => 'get',
                'id' => 'village_search_form',
                'type' => ActiveForm::TYPE_INLINE,
                'fieldConfig' => ['autoPlaceholder' => false]
    ]);
    ?>
    <div class="filter-row">
        <div class="filter-group">
            <div class="filter-group-title">
                Тип недвижимости:
            </div>
            <div class="filter-group-body">
                <div class="btn-group">
                    <span class="btn btn-default active">Дома</span>
                    <?= Html::a("Участки", ['category/filter', 'type_id' => Category::TYPE_STEAD], ['class' => "btn btn-default"]); ?>
                    <?= Html::a("Таунхаусы", ['category/filter', 'type_id' => Category::TYPE_TOWNHOUSE], ['class' => "btn btn-default"]); ?>
                </div>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Цена, руб:
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][price][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['price'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                -
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][price][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['price'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Дом, м<sup>2</sup>: 
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][house_area][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['house_area'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                - 
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][house_area][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['house_area'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Участок, соток:
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][stead_area][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['stead_area'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                - 
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][stead_area][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['stead_area'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
    </div>
    <div class="filter-row">
        <div class="filter-group">
            <div class="filter-group-title">
                Шоссе:
            </div>
            <div class="filter-group-body">
                <?= Html::dropDownList('filter[' . CategoryFilter::TYPE_FIELD_TAG . '][9]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_FIELD_TAG], 9), $fields[9]['values'], ['prompt' => '-выбрать-', 'class' => 'form-control']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Район:
            </div>
            <div class="filter-group-body">
                <?= Html::dropDownList('filter[' . CategoryFilter::TYPE_FIELD_TAG . '][7]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_FIELD_TAG], 7), $fields[7]['values'], ['prompt' => '-выбрать-', 'class' => 'form-control']) ?>
            </div>
        </div>
    </div>

    <div class="filter-row clearfix">
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <input type="submit" class="hidden">
                <?=
                Html::a('Подобрать ' . mb_convert_case($category->topLevel->title, MB_CASE_LOWER, "utf8"), '', [
                    'onclick' => "village_search_form.submit(); return false;",
                    'class' => 'btn btn-sm btn-green'
                ])
                ?>
            </div>
        </div>
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <?= Html::resetButton("Сбросить", ['class' => 'btn btn-default']) ?>&nbsp;
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

frontend/views/category/_realt_search.php
<?php

use common\helpers\Html;
use kartik\widgets\ActiveForm;
?>

<div class="filter clearfix">
    <?php
    $form = ActiveForm::begin([
                'method' => 'get',
                'id' => 'village_search_form',
                'type' => ActiveForm::TYPE_INLINE,
                'fieldConfig' => ['autoPlaceholder' => false]
    ]);
    ?>
    <div class="filter-row">
        <div class="filter-group">
            <div class="filter-group-title">
                Тип недвижимости:
            </div>
            <div class="filter-group-body">
                <div class="btn-group"><a class="btn btn-default" href="#">Дома</a><a class="btn btn-default" href="#">Участки</a><a class="btn btn-default" href="#">Таунхаусы</a></div>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Цена, руб:
            </div>
            <div class="filter-group-body">
                <?= $form->field($model, 'price_from')->textInput(['class' => 'form-control size2', 'placeholder' => 'От']); ?>
                -
                <?= $form->field($model, 'price_to')->textInput(['class' => 'form-control size2', 'placeholder' => 'До']); ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Дом, м<sup>2</sup>: 
            </div>
            <div class="filter-group-body">
                <?= $form->field($model, 'house_area_from')->textInput(['class' => 'form-control size1', 'placeholder' => 'От']); ?> - 
                <?= $form->field($model, 'house_area_to')->textInput(['class' => 'form-control size1', 'placeholder' => 'До']); ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Участок, соток:
            </div>
            <div class="filter-group-body">
                <?= $form->field($model, 'stead_area_from')->textInput(['class' => 'form-control size1', 'placeholder' => 'От']); ?> - 
                <?= $form->field($model, 'stead_area_to')->textInput(['class' => 'form-control size1', 'placeholder' => 'До']); ?>
            </div>
        </div>
    </div>

    <div class="filter-row">
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <input type="submit" class="hidden">
                <?=
                Html::a('Подобрать ' . mb_convert_case($category->topLevel->title, MB_CASE_LOWER, "utf8"), '', [
                    'onclick' => "village_search_form.submit(); return false;",
                    'class' => 'btn btn-sm btn-green'
                ])
                ?>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

frontend/views/category/_realt_stead_search.php
<?php

use common\helpers\Html;
use kartik\widgets\ActiveForm;
use common\models\Category;
use yii\helpers\ArrayHelper;
use common\models\CategoryFilter;
?>

<div class="filter clearfix">
    <?php
    $form = ActiveForm::begin([
                'method' => 'get',
                'id' => 'village_search_form',
                'type' => ActiveForm::TYPE_INLINE,
                'fieldConfig' => ['autoPlaceholder' => false]
    ]);
    ?>
    <div class="filter-row">
        <div class="filter-group">
            <div class="filter-group-title">
                Тип недвижимости:
            </div>
            <div class="filter-group-body">
                <div class="btn-group">
                    <?= Html::a("Дома", ['category/filter', 'type_id' => Category::TYPE_COTTAGE], ['class' => "btn btn-default"]); ?>
                    <span class='btn btn-default active'>Участки</span>
                    <?= Html::a("Таунхаусы", ['category/filter', 'type_id' => Category::TYPE_TOWNHOUSE], ['class' => "btn btn-default"]); ?>
                </div>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Цена, руб:
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][price][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['price'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                -
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][price][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['price'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Участок, соток:
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][stead_area][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['stead_area'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                - 
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][stead_area][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['stead_area'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Шоссе:
            </div>
            <div class="filter-group-body">
                <?= Html::dropDownList('filter[' . CategoryFilter::TYPE_FIELD_TAG . '][9]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_FIELD_TAG], 9), $fields[9]['values'], ['prompt' => '-выбрать-', 'class' => 'form-control']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Район:
            </div>
            <div class="filter-group-body">
                <?= Html::dropDownList('filter[' . CategoryFilter::TYPE_FIELD_TAG . '][7]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_FIELD_TAG], 7), $fields[7]['values'], ['prompt' => '-выбрать-', 'class' => 'form-control']) ?>
            </div>
        </div>
    </div>
    <div class="filter-row clearfix">
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <input type="submit" class="hidden">
                <?=
                Html::a('Подобрать ' . mb_convert_case($category->topLevel->title, MB_CASE_LOWER, "utf8"), '', [
                    'onclick' => "village_search_form.submit(); return false;",
                    'class' => 'btn btn-sm btn-green'
                ])
                ?>
            </div>
        </div>
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <?= Html::resetButton("Сбросить", ['class' => 'btn btn-default']) ?>&nbsp;
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

frontend/views/category/_realt_townhouse_search.php
<?php

use common\helpers\Html;
use kartik\widgets\ActiveForm;
use common\models\Category;
use yii\helpers\ArrayHelper;
use common\models\CategoryFilter;
?>

<div class="filter clearfix">
    <?php
    $form = ActiveForm::begin([
                'method' => 'get',
                'id' => 'village_search_form',
                'type' => ActiveForm::TYPE_INLINE,
                'fieldConfig' => ['autoPlaceholder' => false]
    ]);
    ?>
    <div class="filter-row">
        <div class="filter-group">
            <div class="filter-group-title">
                Тип недвижимости:
            </div>
            <div class="filter-group-body">
                <div class="btn-group">
                    <?= Html::a("Дома", ['category/filter', 'type_id' => Category::TYPE_COTTAGE], ['class' => "btn btn-default"]); ?>
                    <?= Html::a("Участки", ['category/filter', 'type_id' => Category::TYPE_STEAD], ['class' => "btn btn-default"]); ?>
                    <span class='btn btn-default active'>Таунхаусы</span>

                </div>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Цена, руб:
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][price][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['price'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                -
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][price][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['price'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Дом, м<sup>2</sup>: 
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][house_area][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['house_area'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                - 
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][house_area][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['house_area'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Участок, соток:
            </div>
            <div class="filter-group-body">
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][stead_area][from]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['stead_area'], 'from'), ['class' => 'form-control size2', 'placeholder' => 'От']) ?>
                - 
                <?= Html::textInput('filter[' . CategoryFilter::TYPE_CUSTOM . '][stead_area][to]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_CUSTOM]['stead_area'], 'to'), ['class' => 'form-control size2', 'placeholder' => 'До']) ?>
            </div>
        </div>
    </div>
    <div class="filter-row">
        <div class="filter-group">
            <div class="filter-group-title">
                Шоссе:
            </div>
            <div class="filter-group-body">
                <?= Html::dropDownList('filter[' . CategoryFilter::TYPE_FIELD_TAG . '][9]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_FIELD_TAG], 9), $fields[9]['values'], ['prompt' => '-выбрать-', 'class' => 'form-control']) ?>
            </div>
        </div>
        <div class="filter-group">
            <div class="filter-group-title">
                Район:
            </div>
            <div class="filter-group-body">
                <?= Html::dropDownList('filter[' . CategoryFilter::TYPE_FIELD_TAG . '][7]', ArrayHelper::getValue($filter[CategoryFilter::TYPE_FIELD_TAG], 7), $fields[7]['values'], ['prompt' => '-выбрать-', 'class' => 'form-control']) ?>
            </div>
        </div>
    </div>

    <div class="filter-row">
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <input type="submit" class="hidden">
                <?=
                Html::a('Подобрать ' . mb_convert_case($category->topLevel->title, MB_CASE_LOWER, "utf8"), '', [
                    'onclick' => "village_search_form.submit(); return false;",
                    'class' => 'btn btn-sm btn-green'
                ])
                ?>
            </div>
        </div>
        <div class="filter-group pull-right">
            <div class="filter-group-title">&nbsp;</div>
            <div class="filter-group-body">              
                <?= Html::resetButton("Сбросить", ['class' => 'btn btn-default']) ?>&nbsp;
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>